# These are supported funding model platforms
# GitHub displays a "Sponsor" button on your repo based on this file.
 
# github: carlosyv            # Your GitHub Sponsors username (0% fees)
ko_fi: carlosyv  # Uncomment and add your handle once your Ko-fi page is live
