"""initial tables

Revision ID: 70a0cd85ce59
Revises: 
Create Date: 2026-03-19 13:09:18.152787
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70a0cd85ce59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_countries',
    sa.Column('iso3_code', sa.String(length=3), nullable=False),
    sa.Column('iso2_code', sa.String(length=2), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('income_level', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('iso3_code')
    )
    op.create_table('wb_download_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('indicator_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('country_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('year_start', sa.SmallInteger(), nullable=True),
    sa.Column('year_end', sa.SmallInteger(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('completed_requests', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_sources',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_indicators',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['wb_sources.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_wb_indicators_name_trgm', 'wb_indicators', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_wb_indicators_source_id'), 'wb_indicators', ['source_id'], unique=False)
    op.create_table('wb_data_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('indicator_code', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('download_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['wb_countries.iso3_code'], ),
    sa.ForeignKeyConstraint(['download_job_id'], ['wb_download_jobs.id'], ),
    sa.ForeignKeyConstraint(['indicator_code'], ['wb_indicators.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code', 'country_code', 'year', name='uq_data_point')
    )
    op.create_index('ix_data_indicator_country', 'wb_data_points', ['indicator_code', 'country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_indicator_country', table_name='wb_data_points')
    op.drop_table('wb_data_points')
    op.drop_index(op.f('ix_wb_indicators_source_id'), table_name='wb_indicators')
    op.drop_index('ix_wb_indicators_name_trgm', table_name='wb_indicators', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('wb_indicators')
    op.drop_table('wb_sources')
    op.drop_table('wb_download_jobs')
    op.drop_table('wb_countries')
    # ### end Alembic commands ###
